version: 2

builds:
  - binary: freee
    ldflags:
      - -s -w -X github.com/planitaicojp/freee-cli/cmd.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

brews:
  - repository:
      owner: planitaicojp
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    name: freee
    homepage: "https://planitaicojp.github.io/freee-cli-pages/"
    description: "CLI tool for freee public API"
    license: "Apache-2.0"
    install: |
      bin.install "freee"

scoops:
  - repository:
      owner: planitaicojp
      name: bucket
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    name: freee
    homepage: "https://planitaicojp.github.io/freee-cli-pages/"
    description: "CLI tool for freee public API"
    license: "Apache-2.0"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
